In [1]:
#【例4.1】读取素材CatInfo.csv，把数据进行归一化处理。
import pandas as pd
def MaxMinNormalization(x):
    shapeX = x.shape 
    rows = shapeX[0]  #行数
    cols = shapeX[1]   #列数
    headers=list(x)     #Header行
    result =pd.DataFrame(columns=headers)  #存放结果的空DataFrame
    for i in range(0,rows,1):        
        dict1={}                        #存放每一行结果的字典
        dict1[headers[0]]=i
        for j in range(1,cols,1):            
            maxCol=x[headers[j]].max()  #j列最大值
            minCol=x[headers[j]].min()   #j列最小值
            val= (x.iloc[i,j]- minCol)/(maxCol-minCol)  #i行j列数据的归一化结果
            dict1[headers[j]]=val                    
        result=result.append(dict1,ignore_index=True)   #把i行结果添加到result
    return result

data1 = pd.read_csv('CatInfo.csv')
print('original data:\n',data1)
newData=MaxMinNormalization(data1)
print('Normalized data:\n',newData)


original data:
    No  Lwsk  LEar  Weight
0   1  34.0    82    3520
1   2   NaN    63    4490
2   3  45.0    90    2480
3   4  28.0    91    4030
4   5  37.0    59    8000
5   6  39.0    52    6130
6   7  48.0    52    5310
7   8  47.0    49    5280
Normalized data:
     No  Lwsk      LEar    Weight
0  0.0  0.30  0.785714  0.188406
1  1.0   NaN  0.333333  0.364130
2  2.0  0.85  0.976190  0.000000
3  3.0  0.00  1.000000  0.280797
4  4.0  0.45  0.238095  1.000000
5  5.0  0.55  0.071429  0.661232
6  6.0  1.00  0.071429  0.512681
7  7.0  0.95  0.000000  0.507246


In [2]:
#【例4.2】去除数据集的空值并进行归一化处理。
from sklearn import preprocessing
import pandas as pd
data1 = pd.read_csv('CatInfo.csv')
x=data1.dropna(axis=0)  #去除含有空值的行

min_max_scaler = preprocessing.MinMaxScaler()
x_minmax = min_max_scaler.fit_transform(x)
print(x_minmax)


[[0.         0.3        0.78571429 0.1884058 ]
 [0.28571429 0.85       0.97619048 0.        ]
 [0.42857143 0.         1.         0.2807971 ]
 [0.57142857 0.45       0.23809524 1.        ]
 [0.71428571 0.55       0.07142857 0.66123188]
 [0.85714286 1.         0.07142857 0.51268116]
 [1.         0.95       0.         0.50724638]]


In [4]:
#【例4.4】使用SKlearn的preprocessing模块对数据进行标准化处理。
from sklearn import preprocessing
import numpy as np
x = np.array([[3.0,-2.0,490.0],
            [3.0,0.5,520.0],
            [1.0,2.0,-443.0]])
x_scaled = preprocessing.scale(x)
print(x_scaled)


[[ 0.70710678 -1.31319831  0.67328879]
 [ 0.70710678  0.20203051  0.74039398]
 [-1.41421356  1.1111678  -1.41368277]]


In [5]:
#【例4.5】使用preprocessing的MinMaxScaler类，将数据缩放到固定区间，默认缩放到区间 [0，1]。
from sklearn import preprocessing
import numpy as np
x = np.array([[3.0,-2.0,490.0],
            [3.0,0.5,520.0],
            [1.0,2.0,-443.0]])
min_max_scaler = preprocessing.MinMaxScaler()
x_minmax = min_max_scaler.fit_transform(x)
print(x_minmax)


[[1.         0.         0.96884735]
 [1.         0.625      1.        ]
 [0.         1.         0.        ]]


In [6]:
#【例4.6】使用preprocessing的StandardScaler标准化类。
from sklearn import preprocessing
import numpy as np
x = np.array([[3.0,-2.0,490.0],
            [3.0,0.5,520.0],
            [1.0,2.0,-443.0]])
scaler = preprocessing.StandardScaler().fit(x)
scaler.transform(x)  
print(x)


[[ 3.00e+00 -2.00e+00  4.90e+02]
 [ 3.00e+00  5.00e-01  5.20e+02]
 [ 1.00e+00  2.00e+00 -4.43e+02]]


In [7]:
#【例4.7】将猫的数据集拆分成训练集和测试集。
import pandas as pd
from sklearn.model_selection import train_test_split
#导入数据
data = pd.read_csv('CatInfo.csv',",")
df=pd.DataFrame(data)
# 划分成测试集和训练集
cat_train_X , cat_test_X, cat_train_y ,cat_test_y = train_test_split(df['Lwsk'], df['LEar'], test_size=0.3,random_state=0)
# 依次查看训练数据、训练标签、测试数据、测试标签
print('cat_train_X',cat_train_X)
print('cat_train_y',cat_train_y)
print('cat_test_X',cat_test_X)
print('cat_test_y',cat_test_y)


cat_train_X 7    47.0
3    28.0
0    34.0
5    39.0
4    37.0
Name: Lwsk, dtype: float64
cat_train_y 7    49
3    91
0    82
5    52
4    59
Name: LEar, dtype: int64
cat_test_X 6    48.0
2    45.0
1     NaN
Name: Lwsk, dtype: float64
cat_test_y 6    52
2    90
1    63
Name: LEar, dtype: int64


In [8]:
#【例4.8】算法精确率评估。
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
print(classification_report(y_true, y_pred))


             precision    recall  f1-score   support

          0       0.50      1.00      0.67         1
          1       0.00      0.00      0.00         1
          2       1.00      0.67      0.80         3

avg / total       0.70      0.60      0.61         5

